include setting/version.conf
SHELL=/bin/bash
PHONY=default app-build app-up app-down test-build test-up test-down view-build view-compile view-compile-minify view-watch init lint doc-generate doc-publish clean help
XDEVKIT_SETTING_VERSION=v0.24
XDEVKIT_VERSION=v0.24

.PHONY: $(PHONY)

default: app-up

app-build: init-xdevkit docker-compose-build-app
app-up: init-common docker-compose-up-app
app-down: docker-compose-down-app

test-build: init-xdevkit docker-compose-build-test
test-up: init-common docker-compose-up-test
test-down: docker-compose-down-test

view-build: init-xdevkit docker-compose-build-view
view-compile: docker-compose-up-view-compile
view-compile-minify: docker-compose-up-view-compile-minify
view-watch: docker-compose-up-view-watch

init: init-xdevkit init-common

lint: init-xdevkit init-common docker-compose-up-lint
doc-generate: docker-compose-up-doc-generate
doc-publish: docker-compose-up-doc-publish

clean: app-down test-down

help:
	@echo "Usage: make (app|test)-(build|up|down)"
	@echo "Usage: make view-(build|compile|compile-minify|watch)"
	@echo "Usage: make doc-(generate|publish)"
	@echo "Usage: make (init|lint|clean)"
	@echo "Example:"
	@echo "  make app-build             # Recreate image"
	@echo "  make app-up                # Start server"
	@echo "  make app-down              # Clean app container/volume"
	@echo "------------------------------"
	@echo "  make test-build            # Recreate test image"
	@echo "  make test-up               # Start test"
	@echo "  make test-down             # Clean test container/volume"
	@echo "------------------------------"
	@echo "  make view-build            # build view compiler image"
	@echo "  make view-compile          # compile"
	@echo "  make view-compile-minify   # compile minify"
	@echo "  make view-watch            # watch"
	@echo "------------------------------"
	@echo "  make doc-generate     		  # doc-generate"
	@echo "  make doc-deploy     		    # doc-deploy"
	@echo "------------------------------"
	@echo "  make init                  # Update xdevkit, common"
	@echo "------------------------------"
	@echo "  make lint     		          # lint"
	@echo "------------------------------"
	@echo "  make clean                 # Clean app, test container/volume"


# init
init-xdevkit:
	git submodule update -i && pushd ./common/xdevkit-setting/ && git checkout master && git pull && git checkout ${XDEVKIT_SETTING_VERSION} && git pull origin ${XDEVKIT_SETTING_VERSION} && yarn install && popd
	cp ./common/xdevkit-setting/browserServerSetting.js ./staticWeb/view/src/js/_setting/browserServerSetting.js
	cp ./common/xdevkit-setting/browserServerSetting.js ./staticWeb/setting/browserServerSetting.js
	cp ./common/xdevkit-setting/browserServerSetting.js ./authApi/setting/browserServerSetting.js
	cp ./common/xdevkit-setting/browserServerSetting.js ./storageApi/setting/browserServerSetting.js
	git submodule update -i && pushd ./common/xdevkit/ && git checkout master && git pull && git checkout ${XDEVKIT_VERSION} && git pull origin ${XDEVKIT_VERSION} && yarn install && popd
	cp -r ./common/xdevkit/view/src/js/_xdevkit ./staticWeb/view/src/js/_lib/
 
init-common:
	mkdir -p authApi/lib/ && cp common/backend-server/lib.js authApi/lib/backendServerLib.js
	mkdir -p storageApi/lib/ && cp common/backend-server/lib.js storageApi/lib/backendServerLib.js
	sed -i '1s/^/\/* DO NOT EDIT THIS FILE. *\/\n/' authApi/lib/backendServerLib.js
	sed -i '1s/^/\/* DO NOT EDIT THIS FILE. *\/\n/' storageApi/lib/backendServerLib.js
	mkdir -p authApi/input/ && cp common/backend-server/input.js authApi/input/backendServerInput.js
	mkdir -p storageApi/input/ && cp common/backend-server/input.js storageApi/input/backendServerInput.js
	sed -i '1s/^/\/* DO NOT EDIT THIS FILE. *\/\n/' authApi/input/backendServerInput.js
	sed -i '1s/^/\/* DO NOT EDIT THIS FILE. *\/\n/' storageApi/input/backendServerInput.js
	sleep 1


# build
docker-compose-build-app:
	docker compose -p xlogin-jp-app -f ./docker/docker-compose.app.yml build
docker-compose-build-test:
	docker compose -p xlogin-jp-test -f ./docker/docker-compose.test.yml build
docker-compose-build-view:
	docker compose -p xlogin-jp-view -f ./docker/docker-compose.view.yml build

# up
docker-compose-up-app:
	docker compose -p xlogin-jp-app -f ./docker/docker-compose.app.yml up
docker-compose-up-test:
	docker compose -p xlogin-jp-test -f ./docker/docker-compose.test.yml down
	docker volume rm xlogin-jp-test_xltest-volume-pc-psql || true
	docker volume rm xlogin-jp-test_xltest-volume-rc-redis || true
	docker compose -p xlogin-jp-test -f ./docker/docker-compose.test.yml up --abort-on-container-exit

docker-compose-up-view-compile:
	BUILD_COMMAND="compile" docker compose -p xlogin-jp-view -f ./docker/docker-compose.view.yml up --abort-on-container-exit
docker-compose-up-view-compile-minify:
	BUILD_COMMAND="compile-minify" docker compose -p xlogin-jp-view -f ./docker/docker-compose.view.yml up --abort-on-container-exit
docker-compose-up-view-watch:
	BUILD_COMMAND="watch" docker compose -p xlogin-jp-view -f ./docker/docker-compose.view.yml up --abort-on-container-exit

# down
docker-compose-down-app:
	docker compose -p xlogin-jp-app -f ./docker/docker-compose.app.yml down --volumes
docker-compose-down-test:
	docker compose -p xlogin-jp-test -f ./docker/docker-compose.test.yml down --volumes

# devtool
docker-compose-up-lint:
	docker compose -p xlogin-jp-lint -f ./docker/docker-compose.lint.yml up --abort-on-container-exit
docker-compose-up-doc-generate:
	BUILD_COMMAND="doc-generate" docker compose -p xlogin-jp-doc -f ./docker/docker-compose.doc.yml up
docker-compose-up-doc-publish:
	BUILD_COMMAND="doc-publish" docker compose -p xlogin-jp-doc -f ./docker/docker-compose.doc.yml up



%:
	@echo "Target '$@' does not exist."
	@make -s help

