include setting/version.conf
SHELL=/bin/bash
PHONY=default app-rebuild app-build app-up app-up-d app-down test-build test-up test-down view-build view-compile view-compile-minify view-watch init lint doc-generate doc-publish clean add-client show-client help

.PHONY: $(PHONY)

default: app-up

app-rebuild: app-down app-build
app-build: init-xdevkit docker-compose-build-app
app-up: init-common docker-compose-up-app
app-up-d: init-common docker-compose-up-app-d
app-down: docker-compose-down-app

test-build: init-xdevkit docker-compose-build-test
test-up: init-common docker-compose-up-test
test-down: docker-compose-down-test

view-build: init-xdevkit docker-compose-build-view
view-compile: docker-compose-up-view-compile
view-compile-minify: docker-compose-up-view-compile-minify
view-watch: docker-compose-up-view-watch

init: init-xdevkit init-common

lint: init-xdevkit init-common docker-compose-up-lint
doc-generate: docker-compose-up-doc-generate
doc-publish: docker-compose-up-doc-publish

clean: app-down test-down

add-client: psql-add-client
show-client: psql-show-client

help:
	@echo "Usage: make (app|test)-(rebuild|build|up|down)"
	@echo "Usage: make view-(build|compile|compile-minify|watch)"
	@echo "Usage: make doc-(generate|publish)"
	@echo "Usage: make (init|lint|clean)"
	@echo "Example:"
	@echo "  make app-rebuild           # Recreate image"
	@echo "  make app-build             # Create image"
	@echo "  make app-up                # Start server"
	@echo "  make app-up-d              # Start server and detatch"
	@echo "  make app-down              # Clean app container/volume"
	@echo "------------------------------"
	@echo "  make test-build            # Recreate test image"
	@echo "  make test-up               # Start test"
	@echo "  make test-down             # Clean test container/volume"
	@echo "------------------------------"
	@echo "  make view-build            # build view compiler image"
	@echo "  make view-compile          # compile"
	@echo "  make view-compile-minify   # compile minify"
	@echo "  make view-watch            # watch"
	@echo "------------------------------"
	@echo "  make doc-generate     		  # doc-generate"
	@echo "  make doc-deploy     		    # doc-deploy"
	@echo "------------------------------"
	@echo "  make init                  # Update xdevkit, common"
	@echo "------------------------------"
	@echo "  make lint     		          # lint"
	@echo "------------------------------"
	@echo "  make add-client	          # add client after container up"
	@echo "  make show-client	          # show client after container up"
	@echo "------------------------------"
	@echo "  make clean                 # Clean app, test container/volume"


# init
init-xdevkit:
	git submodule update -i && pushd ./xdevkit-backend/common/xdevkit-setting/ && git checkout master && git pull && git checkout ${XDEVKIT_SETTING_VERSION} && git pull origin ${XDEVKIT_SETTING_VERSION} && yarn install && popd
	cp ./xdevkit-backend/common/xdevkit-setting/browserServerSetting.js ./service/staticWeb/src/view/src/js/_setting/browserServerSetting.js
	cp ./xdevkit-backend/common/xdevkit-setting/browserServerSetting.js ./service/staticWeb/src/setting/browserServerSetting.js
	cp ./xdevkit-backend/common/xdevkit-setting/browserServerSetting.js ./service/authApi/src/setting/browserServerSetting.js
	cp ./xdevkit-backend/common/xdevkit-setting/browserServerSetting.js ./service/storageApi/src/setting/browserServerSetting.js
	
	git submodule update -i && pushd ./xdevkit-backend/common/xdevkit-view-component/ && git checkout master && git pull && git checkout ${XDEVKIT_VIEW_COMPONENT_VERSION} && git pull origin ${XDEVKIT_VIEW_COMPONENT_VERSION} && yarn install && popd
	cp -r ./xdevkit-backend/common/xdevkit-view-component/src/js/_xdevkit ./service/staticWeb/src/view/src/js/_lib/
 
init-common:
	mkdir -p ./service/authApi/src/lib/ && cp ./xdevkit-backend/common/backend-server/lib.js ./service/authApi/src/lib/backendServerLib.js
	mkdir -p ./service/storageApi/src/lib/ && cp ./xdevkit-backend/common/backend-server/lib.js ./service/storageApi/src/lib/backendServerLib.js
	sed -i '1s/^/\/* DO NOT EDIT THIS FILE. *\/\n/' ./service/authApi/src/lib/backendServerLib.js
	sed -i '1s/^/\/* DO NOT EDIT THIS FILE. *\/\n/' ./service/storageApi/src/lib/backendServerLib.js
	mkdir -p ./service/authApi/src/input/ && cp ./xdevkit-backend/common/backend-server/input.js ./service/authApi/src/input/backendServerInput.js
	mkdir -p ./service/storageApi/src/input/ && cp ./xdevkit-backend/common/backend-server/input.js ./service/storageApi/src/input/backendServerInput.js
	sed -i '1s/^/\/* DO NOT EDIT THIS FILE. *\/\n/' ./service/authApi/src/input/backendServerInput.js
	sed -i '1s/^/\/* DO NOT EDIT THIS FILE. *\/\n/' ./service/storageApi/src/input/backendServerInput.js
	mkdir -p ./service/authApi/src/output/ && cp ./xdevkit-backend/common/backend-server/output.js ./service/authApi/src/output/backendServerOutput.js
	mkdir -p ./service/storageApi/src/output/ && cp ./xdevkit-backend/common/backend-server/output.js ./service/storageApi/src/output/backendServerOutput.js
	sed -i '1s/^/\/* DO NOT EDIT THIS FILE. *\/\n/' ./service/authApi/src/output/backendServerOutput.js
	sed -i '1s/^/\/* DO NOT EDIT THIS FILE. *\/\n/' ./service/storageApi/src/output/backendServerOutput.js
	mkdir -p ./service/authApi/src/core/ && cp ./xdevkit-backend/common/backend-server/core.js ./service/authApi/src/core/backendServerCore.js
	mkdir -p ./service/storageApi/src/core/ && cp ./xdevkit-backend/common/backend-server/core.js ./service/storageApi/src/core/backendServerCore.js
	sed -i '1s/^/\/* DO NOT EDIT THIS FILE. *\/\n/' ./service/authApi/src/core/backendServerCore.js
	sed -i '1s/^/\/* DO NOT EDIT THIS FILE. *\/\n/' ./service/storageApi/src/core/backendServerCore.js
	@sleep 1


# build
docker-compose-build-app:
	docker compose -p xlogin-jp-app -f ./app/docker/docker-compose.app.yml build
docker-compose-build-test:
	docker compose -p xlogin-jp-test -f ./app/docker/docker-compose.test.yml build
docker-compose-build-view:
	docker compose -p xlogin-jp-view -f ./app/docker/docker-compose.view.yml build

# up
docker-compose-up-app:
	docker compose -p xlogin-jp-app -f ./app/docker/docker-compose.app.yml up
docker-compose-up-app-d:
	docker compose -p xlogin-jp-app -f ./app/docker/docker-compose.app.yml up -d
docker-compose-up-test:
	docker compose -p xlogin-jp-test -f ./app/docker/docker-compose.test.yml down
	docker volume rm xlogin-jp-test_xltest-volume-pc-psql || true
	docker volume rm xlogin-jp-test_xltest-volume-rc-redis || true
	docker compose -p xlogin-jp-test -f ./app/docker/docker-compose.test.yml up --abort-on-container-exit

docker-compose-up-view-compile:
	BUILD_COMMAND="compile" docker compose -p xlogin-jp-view -f ./app/docker/docker-compose.view.yml up --abort-on-container-exit
docker-compose-up-view-compile-minify:
	BUILD_COMMAND="compile-minify" docker compose -p xlogin-jp-view -f ./app/docker/docker-compose.view.yml up --abort-on-container-exit
docker-compose-up-view-watch:
	BUILD_COMMAND="watch" docker compose -p xlogin-jp-view -f ./app/docker/docker-compose.view.yml up --abort-on-container-exit

# down
docker-compose-down-app:
	docker compose -p xlogin-jp-app -f ./app/docker/docker-compose.app.yml down --volumes
docker-compose-down-test:
	docker compose -p xlogin-jp-test -f ./app/docker/docker-compose.test.yml down --volumes

# devtool
psql-add-client:
	./service/postgresql/bin/addNewClient.sh

psql-show-client:
	./service/postgresql/bin/showClientInfo.sh

%:
	@echo "Target '$@' does not exist."
	@make -s help

