version: '3'

services:
  redis_container:
    container_name: xltest-container-redis
    build:
      context: ../
      dockerfile: ./docker/redisContainer/Dockerfile
    volumes:
      - xltest-volume-rc-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]

  psql_container:
    container_name: xltest-container-psql
    build:
      context: ../
      dockerfile: ./docker/psqlContainer/Dockerfile
    volumes:
      - xltest-volume-pc-psql:/var/lib/postgresql/data
      - ../psql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=psqladmin
      - POSTGRES_PASSWORD=psqlpass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 30

  auth_api_container:
    container_name: xltest-container-auth-api
    build:
      context: ../
      dockerfile: ./docker/authApiContainer/Dockerfile
    tty: true
    volumes:
      - ../authApi:/app
      - xltest-volume-aac-nm:/app/node_modules
    command: sh -c "rm /tmp/test.done || true && yarn run test && echo 0 > /tmp/test.done && sleep infinity"
    healthcheck:
      test: ls /tmp/test.done
      interval: 5s
      timeout : 5s
      retries: 10
    depends_on:
      redis_container: 
        condition: service_healthy
      psql_container:
        condition: service_healthy

  storage_api_container:
    container_name: xltest-container-storage-api
    build:
      context: ../
      dockerfile: ./docker/storageApiContainer/Dockerfile
    tty: true
    volumes:
      - ../storageApi:/app
      - xltest-volume-sac-nm:/app/node_modules
    environment:
     - IS_TEST=true
    command: sh -c "yarn run test"
    depends_on:
      redis_container: 
        condition: service_healthy
      psql_container:
        condition: service_healthy
      auth_api_container:
        condition: service_healthy

volumes:
  xltest-volume-rc-redis:
  xltest-volume-pc-psql:
  xltest-volume-aac-nm:
  xltest-volume-sac-nm:


