version: '3'

services:
  static_web_container:
    container_name: xldoc-container-static-web
    build:
      context: ../
      dockerfile: ./docker/staticWebContainer/Dockerfile
    tty: true
    volumes:
      - ../staticWeb:/app
      - xlcommon-volume-swc-nm:/app/node_modules
    environment:
     - IS_TEST=false
    command: sh -c "yarn run doc-generate"

  auth_api_container:
    container_name: xldoc-container-auth-api
    build:
      context: ../
      dockerfile: ./docker/authApiContainer/Dockerfile
    tty: true
    volumes:
      - ../authApi:/app
      - xlcommon-volume-aac-nm:/app/node_modules
    environment:
     - IS_TEST=false
    command: sh -c "yarn run doc-generate"

  storage_api_container:
    container_name: xldoc-container-storage-api
    build:
      context: ../
      dockerfile: ./docker/storageApiContainer/Dockerfile
    tty: true
    volumes:
      - ../storageApi:/app
      - xlcommon-volume-sac-nm:/app/node_modules
    environment:
     - IS_TEST=false
    command: sh -c "yarn run doc-generate"


  jsdoc_container:
    container_name: xldoc-container-jsdoc
    build:
      context: ../
      dockerfile: ./docker/docContainer/Dockerfile
    tty: true
    volumes:
      - ../:/app
      - xldoc-volume-jsdoc-nm:/app/node_modules
    environment:
     - IS_TEST=false
    command: sh -c "cd doc/jsdoc/ && make copy-container-jsdoc && yarn run ${BUILD_COMMAND}"
    depends_on:
      static_web_container:
        condition: service_completed_successfully
      auth_api_container:
        condition: service_completed_successfully
      storage_api_container:
        condition: service_completed_successfully


volumes:
  xlcommon-volume-aac-nm:
  xlcommon-volume-sac-nm:
  xlcommon-volume-swc-nm:
  xldoc-volume-jsdoc-nm:

