version: '3'

services:
  static_web_container:
    container_name: xlgendoc-container-static-web
    build:
      context: ../
      dockerfile: ./docker/staticWebContainer/Dockerfile
    tty: true
    volumes:
      - ../staticWeb:/app
      - xlcommon-volume-swc-nm:/app/node_modules
    environment:
     - IS_TEST=false
    command: sh -c "yarn run gendoc"

  auth_api_container:
    container_name: xlgendoc-container-auth-api
    build:
      context: ../
      dockerfile: ./docker/authApiContainer/Dockerfile
    tty: true
    volumes:
      - ../authApi:/app
      - xlcommon-volume-aac-nm:/app/node_modules
    environment:
     - IS_TEST=false
    command: sh -c "yarn run gendoc"

  storage_api_container:
    container_name: xlgendoc-container-storage-api
    build:
      context: ../
      dockerfile: ./docker/storageApiContainer/Dockerfile
    tty: true
    volumes:
      - ../storageApi:/app
      - xlcommon-volume-sac-nm:/app/node_modules
    environment:
     - IS_TEST=false
    command: sh -c "yarn run gendoc"

  jsdoc_container:
    container_name: xlgendoc-container-jsdoc
    build:
      context: ../
      dockerfile: ./docker/gendocContainer/Dockerfile
    tty: true
    volumes:
      - ../doc/jsdoc/:/app
      - ../staticWeb/doc/jsdoc/html/:/app/html/staticWeb
      - ../authApi/doc/jsdoc/html/:/app/html/authApi
      - ../storageApi/doc/jsdoc/html/:/app/html/storageApi
      - xlgendoc-volume-jsdoc-nm:/app/node_modules
    environment:
     - IS_TEST=false
    command: sh -c "yarn run gh-pages-deploy"
    depends_on:
      static_web_container:
        condition: service_completed_successfully
      auth_api_container:
        condition: service_completed_successfully
      storage_api_container:
        condition: service_completed_successfully

volumes:
  xlcommon-volume-aac-nm:
  xlcommon-volume-sac-nm:
  xlcommon-volume-swc-nm:
  xlgendoc-volume-jsdoc-nm:

