version: '3'

services:
  rediscontainer:
    container_name: xlapp-container-redis
    build:
      context: ../
      dockerfile: ./docker/rediscontainer/Dockerfile
    volumes:
      - xlapp-volume-rc-redis:/data
  psqlcontainer:
    container_name: xlapp-container-psql
    build:
      context: ../
      dockerfile: ./docker/psqlcontainer/Dockerfile
    volumes:
      - xlapp-volume-pc-psql:/var/lib/postgresql/data
      - ../psql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=psqladmin
      - POSTGRES_PASSWORD=psqlpass
  webcontainer:
    container_name: xlapp-container-web
    build:
      context: ../
      dockerfile: ./docker/webcontainer/Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ../src:/app
      - xlapp-volume-wc-nm:/app/node_modules
    environment:
     - IS_TEST=false
    command: sh -c "npm run start-watch"
    depends_on:
      - rediscontainer
      - psqlcontainer

volumes:
  xlapp-volume-rc-redis:
  xlapp-volume-pc-psql:
  xlapp-volume-wc-nm:


