version: '3'

services:
  redis_container:
    container_name: xlapp-container-redis
    build:
      context: ../
      dockerfile: ./docker/redisContainer/Dockerfile
    volumes:
      - xlapp-volume-rc-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]

  psql_container:
    container_name: xlapp-container-psql
    build:
      context: ../
      dockerfile: ./docker/psqlContainer/Dockerfile
    volumes:
      - xlapp-volume-pc-psql:/var/lib/postgresql/data
      - ../psql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "xl_admin", "-d", "xl_db"]
      interval: 5s
      timeout: 5s
      retries: 30

  static_web_container:
    container_name: xlapp-container-static-web
    build:
      context: ../
      dockerfile: ./docker/staticWebContainer/Dockerfile
    ports:
      - 9091:9090
    tty: true
    volumes:
      - ../staticWeb:/app
      - xlapp-volume-swc-nm:/app/node_modules
    environment:
     - IS_TEST=false
    command: sh -c "rm /tmp/setup.done || true && yarn run start-watch"
    healthcheck:
      test: ls /tmp/setup.done
      interval: 5s
      timeout : 5s
      retries: 10

  auth_api_container:
    container_name: xlapp-container-auth-api
    build:
      context: ../
      dockerfile: ./docker/authApiContainer/Dockerfile
    tty: true
    volumes:
      - ../authApi:/app
      - xlapp-volume-aac-nm:/app/node_modules
    environment:
     - IS_TEST=false
    command: sh -c "rm /tmp/setup.done || true && yarn run start-watch"
    depends_on:
      redis_container: 
        condition: service_healthy
      psql_container:
        condition: service_healthy
    healthcheck:
      test: ls /tmp/setup.done
      interval: 5s
      timeout : 5s
      retries: 10

  storage_api_container:
    container_name: xlapp-container-storage-api
    build:
      context: ../
      dockerfile: ./docker/storageApiContainer/Dockerfile
    tty: true
    volumes:
      - ../storageApi:/app
      - xlapp-volume-sac-nm:/app/node_modules
    environment:
     - IS_TEST=false
    command: sh -c "rm /tmp/setup.done || true && yarn run start-watch"
    depends_on:
      auth_api_container: 
        condition: service_healthy
    healthcheck:
      test: ls /tmp/setup.done
      interval: 5s
      timeout : 5s
      retries: 10

  reverse_proxy_container:
    container_name: xlapp-container-reverse-proxy
    build:
      context: ../
      dockerfile: ./docker/reverseProxyContainer/Dockerfile
    ports:
      - 3333:80
    volumes:
      - ../reverseProxy/nginx.conf:/etc/nginx/nginx.conf
      - ../setting/.htpasswd:/etc/nginx/.htpasswd
      - ../reverseProxy/log:/var/log/nginx
    depends_on:
      static_web_container:
        condition: service_healthy
      storage_api_container:
        condition: service_healthy

  prometheus:
    container_name: xlapp-container-prometheus
    image: prom/prometheus
    volumes:
      - ../prometheus/prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090

  node-exporter:
    container_name: xlapp-container-node-exporter
    image: quay.io/prometheus/node-exporter
    ports:
      - 9100:9100

  grafana:
    container_name: xlapp-container-grafana
    image: grafana/grafana
    ports:
      - 3000:3000

  alertmanager:
    container_name: xlapp-container-alertmanager
    image: prom/alertmanager
    volumes:
      - ../prometheus/alertmanager:/etc/alertmanager
    command: "--config.file=/etc/alertmanager/config.yml"
    ports:
      - 9093:9093
    restart: always

volumes:
  xlapp-volume-rc-redis:
  xlapp-volume-pc-psql:
  xlapp-volume-aac-nm:
  xlapp-volume-sac-nm:
  xlapp-volume-swc-nm:


