version: '3'

services:
  static_web_container:
    container_name: xllint-container-static-web
    build:
      context: ../
      dockerfile: ./docker/staticWebContainer/Dockerfile
    tty: true
    volumes:
      - ../staticWeb:/app
      - xlcommon-volume-swc-nm:/app/node_modules
    environment:
     - IS_TEST=false
    command: sh -c "yarn run lint"

  auth_api_container:
    container_name: xllint-container-auth-api
    build:
      context: ../
      dockerfile: ./docker/authApiContainer/Dockerfile
    tty: true
    volumes:
      - ../authApi:/app
      - xlcommon-volume-aac-nm:/app/node_modules
    environment:
     - IS_TEST=false
    command: sh -c "yarn run lint"

  storage_api_container:
    container_name: xllint-container-storage-api
    build:
      context: ../
      dockerfile: ./docker/storageApiContainer/Dockerfile
    tty: true
    volumes:
      - ../storageApi:/app
      - xlcommon-volume-sac-nm:/app/node_modules
    environment:
     - IS_TEST=false
    command: sh -c "yarn run lint"

volumes:
  xlcommon-volume-aac-nm:
  xlcommon-volume-sac-nm:
  xlcommon-volume-swc-nm:


