name: eslint
on: [push]
jobs:
  eslint-staticWeb:
    name: GitHub Actions eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run app
        run: make app-up &
      - name: sleep
        run: sleep 30
      - name: move 1
        run: cd staticWeb
      - name: Run eslint-server @staticWeb
        run: yarn lint-server
      - name: Run eslint-browser @staticWeb
        run: yarn lint-browser

  slack-notification:
    if: always()
    needs:  [eslint-staticWeb]
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      - name: Slack Notification
        uses: sonots/slack-notice-action@v3
        with:
          title: eslint (${{ github.event.repository.name }})
          status: ${{ env.WORKFLOW_CONCLUSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.MY_GITHUB_CHANNEL_WEBHOOK_URL }}

