name: eslint
on: [push]
jobs:

  eslint-staticWeb:
    name: GitHub Actions eslint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: staticWeb
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: yarn install
      - name: Run eslint-server @staticWeb
        run: yarn lint-server
      - name: Run eslint-browser @staticWeb
        run: yarn lint-browser

  eslint-authApi:
    name: GitHub Actions eslint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: authApi
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - name: Run eslint-server @authApi
        run: yarn lint-server

  slack-notification:
    if: always()
    needs:  [eslint-staticWeb, eslint-authApi]
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      - name: Slack Notification
        uses: sonots/slack-notice-action@v3
        with:
          title: eslint (${{ github.event.repository.name }})
          status: ${{ env.WORKFLOW_CONCLUSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.MY_GITHUB_CHANNEL_WEBHOOK_URL }}

